# -*- mode: ruby -*-
# vi: set ft=ruby :

# IP addresses of the injector and server
@lr_subnet = "192.168.56"
@lr_ip_injector = "#{@lr_subnet}.11"
@lr_ip_server = "#{@lr_subnet}.10"

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Use a precise64. You can change that to precise32 if needed
  config.vm.box = "precise64"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  
  config.vm.define :injector do |config|
    config.vm.host_name = "injector"    
    config.vm.network "private_network", ip: @lr_ip_injector    
    config.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--cpus", 1, "--memory", 512]
    end

    config.vm.provision :shell, :privileged => false, :path => "injector.sh"
  end
  
  config.vm.define :server do |config|
    config.vm.host_name = "server"
    config.vm.network "private_network", ip: @lr_ip_server
    config.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--cpus", 3, "--memory", 512]
    end
    
    config.vm.provision :shell, :privileged => false, :path => "server.sh"
  end
end
